{{ if .Values.secrets }}
{{- $ns := $.Release.Namespace }}
{{- $stores := list
  (dict
    "name"        "bitwarden-login"
    "urlPath"     (printf "object/item/{{ .remoteRef.key }}")
    "contentType" "application/json"
    "jsonPath"    "$.data.login.{{ .remoteRef.property }}"
  )
  (dict
    "name"        "bitwarden-fields"
    "urlPath"     (printf "object/item/{{ .remoteRef.key }}")
    "contentType" ""
    "jsonPath"    "$.data.fields[?@.name==\"{{ .remoteRef.property }}\"].value"
  )
  (dict
    "name"        "bitwarden-attachments"
    "urlPath"     (printf "object/attachment/{{ .remoteRef.property }}?itemid={{ .remoteRef.key }}")
    "contentType" ""
    "jsonPath"    ""
  )
}}
{{- range $stores }}
{{- include "extra.clusterSecretStore" (merge . (dict "namespace" $ns)) }}
---
{{- end }}
{{ end }}
