{{- if .Values.ingressAdmin.enabled -}}
{{- $fullName := include "meet.fullname" . -}}
{{- $kubeVersion := .Capabilities.KubeVersion.GitVersion -}}
{{- if and .Values.ingressAdmin.className (not (semverCompare ">=1.18-0" $kubeVersion)) }}
  {{- if not (hasKey .Values.ingressAdmin.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingressAdmin.annotations "kubernetes.io/ingress.class" .Values.ingressAdmin.className}}
  {{- end }}
{{- end }}
apiVersion: {{ include "meet.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ $fullName }}-admin
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "meet.labels" . | nindent 4 }}
  {{- with .Values.ingressAdmin.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ingressAdmin.className (semverCompare ">=1.18-0" $kubeVersion) }}
  ingressClassName: {{ .Values.ingressAdmin.className }}
  {{- end }}
  {{- if .Values.ingressAdmin.tls.enabled }}
  tls:
    {{- if .Values.ingressAdmin.host }}
    - secretName: {{ $fullName }}-tls
    - secretName: {{ .Values.ingressAdmin.tls.secretName | default (printf "%s-tls" $fullName) | quote }}
      hosts:
        - {{ .Values.ingressAdmin.host | quote }}
    {{- end }}
    {{- range .Values.ingressAdmin.tls.additional }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- if .Values.ingressAdmin.host }}
    - host: {{ .Values.ingressAdmin.host | quote }}
      http:
        paths:
          {{- $backendArgs := dict "svcName" (include "meet.backend.fullname" .) "svcPort" .Values.backend.service.port "cap" .Capabilities }}
          - path: {{ .Values.ingressAdmin.path | quote }}
            {{- if semverCompare ">=1.18-0" $kubeVersion }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- include "meet.ingress.backend" $backendArgs | nindent 14 }}
          - path: /static
            {{- if semverCompare ">=1.18-0" $kubeVersion }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- include "meet.ingress.backend" $backendArgs | nindent 14 }}
    {{- end }}
    {{- range .Values.ingressAdmin.hosts }}
    {{- $backendArgs := dict "svcName" (include "meet.backend.fullname" $) "svcPort" $.Values.backend.service.port "cap" $.Capabilities }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: {{ $.Values.ingressAdmin.path | quote }}
            {{- if semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- include "meet.ingress.backend" $backendArgs | nindent 14 }}
    {{- end }}
{{- end }}
